/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Participant = IDL.Principal;
export const MeetingSession = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'participants' : IDL.Vec(Participant),
  'sentimentScore' : IDL.Float64,
  'endTime' : IDL.Opt(Time),
  'cost' : IDL.Float64,
});

export const idlService = IDL.Service({
  'endMeeting' : IDL.Func([IDL.Text], [IDL.Int], []),
  'getAllMeetings' : IDL.Func([], [IDL.Vec(MeetingSession)], ['query']),
  'getMeeting' : IDL.Func([IDL.Text], [MeetingSession], ['query']),
  'signUp' : IDL.Func([IDL.Text], [], []),
  'startMeeting' : IDL.Func([IDL.Text, IDL.Vec(Participant)], [Time], []),
  'updateCost' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updateSentiment' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Participant = IDL.Principal;
  const MeetingSession = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'participants' : IDL.Vec(Participant),
    'sentimentScore' : IDL.Float64,
    'endTime' : IDL.Opt(Time),
    'cost' : IDL.Float64,
  });
  
  return IDL.Service({
    'endMeeting' : IDL.Func([IDL.Text], [IDL.Int], []),
    'getAllMeetings' : IDL.Func([], [IDL.Vec(MeetingSession)], ['query']),
    'getMeeting' : IDL.Func([IDL.Text], [MeetingSession], ['query']),
    'signUp' : IDL.Func([IDL.Text], [], []),
    'startMeeting' : IDL.Func([IDL.Text, IDL.Vec(Participant)], [Time], []),
    'updateCost' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updateSentiment' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };